### PR TITLE
Fix StableTokenBRL error: Catch token not registered error, display non-deployed token in balances

### LINKED ISSUE #146: Switching networks with MetaMask is pretty buggy/inconsistent

### PR DESCRIPTION
**Pull request by zhaonancy**
Fix #146 #178

StableTokenBRL not currently deployed to Baklava, and was receiving `Error: StableTokenBRL not (yet) registered` on the sample app. This change catches the UnregisteredError and shows "not deployed in network" under the token balances.

### CODE REVIEW

File: packages/example/pages/index.tsx [hunk 1]
```diff
@@ -16,7 +16,7 @@ interface Summary {
   address: string;
   wallet: string;
   celo: BigNumber;
-  balances: { symbol: string; value: BigNumber }[];
+  balances: { symbol: StableToken; value: BigNumber | string }[];
```
Comment (nicolasbrugneaux) [inline packages/example/pages/index.tsx]: maybe a nicer way here would be to have `symbol: StableToken, value?: BigNumber, error?: string`

File: packages/example/pages/index.tsx [hunk 2]
```diff
@@ -70,9 +70,15 @@ export default function Home(): React.ReactElement {
       kit.contracts.getGoldToken(),
       Promise.all(
         Object.values(StableToken).map(async (stable) => {
+          let contract;
+          try {
+            contract = await kit.contracts.getStableToken(stable);
+          } catch (e) {
```
Comment (nicolasbrugneaux) [inline packages/example/pages/index.tsx:76]: since it's the example app it's fine, but maybe we could log the error here just in case

Comment (zhaonancy) [reply packages/example/pages/index.tsx:76]: done!

File: packages/example/pages/index.tsx (hunk 1 above)
Comment (zhaonancy) [reply packages/example/pages/index.tsx]: added a commit that changes the value to also be of type string, should it still be split out into `value?: string, error?: string`?

File: packages/example/pages/index.tsx [hunk 3]
```diff
@@ -16,7 +16,7 @@ interface Summary {
   address: string;
   wallet: string;
   celo: BigNumber;
-  balances: { symbol: string; value: BigNumber }[];
+  balances: { symbol: StableToken; value: string }[];
```
Comment (aaronmgdr) [inline packages/example/pages/index.tsx:19]: Having this value sometimes be numberish and sometimes be words worries me a little.

Comment (dckesler) [reply packages/example/pages/index.tsx:19]: This is a pretty good point actually. We should probably have this be either `string` or `null` and then at the point of rendering change `null` to the 'not deployed in network' for the UI.

Comment (nicolasbrugneaux) [reply packages/example/pages/index.tsx:19]: left a similar comment earlier, my suggestion was something like `symbol: StableToken, value?: BigNumber, error?: string`

File: packages/example/pages/index.tsx (hunk 1 above)
Comment (nicolasbrugneaux) [reply packages/example/pages/index.tsx]: left a comment on the not outdate thread. I still think it should be split

File: packages/example/pages/index.tsx (hunk 3 above)
Comment (aaronmgdr) [reply packages/example/pages/index.tsx:19]: GO TO BED

Comment (zhaonancy) [reply packages/example/pages/index.tsx]: Changed to Nico's suggestion!

**Review by aaronmgdr — APPROVED** [review]
